version: "3"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.8-alpine
    command: redis-server
    ports:
      - "6379:6379"

  url_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: url_shortener:latest
    entrypoint: ./entrypoint.sh
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '3000']
    ports:
      - 3000:3000
    volumes:
      - .:/url_shortener
    stdin_open: true
    tty: true
    environment:
      - "RAILS_ENV=development"
      - "RAILS_MAX_THREADS=50"
      - "STORE_SERVICE=redis"
      - "BASE_URL=http://shortener.com"
    depends_on:
      - postgres
      - redis

  url_shortener_sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    image: url_shortener_sidekiq:latest
    command: bundle exec sidekiq
    volumes:
      - .:/url_shortener
    stdin_open: true
    tty: true
    environment:
      - "RAILS_ENV=development"
      - "RAILS_MAX_THREADS=1"
      - "BASE_URL=http://shortener.com"
    depends_on:
      - postgres
      - redis
