version: "3"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  url_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: url_shortener:latest
    entrypoint: ./entrypoint.sh
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '3000']
    ports:
      - 3000:3000
    volumes:
      - .:/url_shortener
    stdin_open: true
    tty: true
    environment:
      - "RAILS_ENV=test"
    depends_on:
      - postgres
